"""
Runner for connected-pair STDP induction simulations using dhuruva_modified_edges.h5.
Thresholds (theta_d/theta_p) and synapse properties (rho0, Use_d/p, gmax_d/p) are read
directly from the edges HDF5 — no EPG calibration step.

Usage (run from the simulation workdir via sbatch --chdir=<workdir>):
    python pairrunner_edges.py --params chindemi --fastforward 280000
    python pairrunner_edges.py --params chindemi  # no fastforward
"""

import os
import sys
import time
import pickle
import argparse
import logging

import plastyfire.simulator_edges as sim_mod

# ── Named parameter presets ──────────────────────────────────────────────────

PARAM_PRESETS = {
    "chindemi": {
        "tau_effca_GB_GluSynapse": 278.3177658387,
        "gamma_d_GB_GluSynapse":   101.5387594661,
        "gamma_p_GB_GluSynapse":   216.1841700668,
        # chindemi uses theta_d/theta_p from edges.h5 (no a-params)
    },
    "fitted": {
        # Best-fit parameters from JAX CICR optimization round 1 (loss = 0.000289)
        "tau_effca_GB_GluSynapse": 200.4818,
        "gamma_d_GB_GluSynapse":    60.6964,
        "gamma_p_GB_GluSynapse":   178.2431,
        # a-params: theta_d/theta_p computed per-synapse from c_pre/c_post
        "a00": 0.7967, "a01": 1.1547,
        "a10": 1.1382, "a11": 1.9027,
        "a20": 2.2637, "a21": 7.0244,
        "a30": 3.5947, "a31": 6.2696,
    },
    "fitting2": {
        # Best-fit parameters from JAX CICR optimization round 2 (differential_evolution, loss=0.0366)
        "tau_effca_GB_GluSynapse": 308.0155,
        "gamma_d_GB_GluSynapse":    76.1153,
        "gamma_p_GB_GluSynapse":   181.0415,
        # a-params: theta_d/theta_p computed per-synapse from c_pre/c_post
        "a00": 1.0378, "a01": 1.2593,
        "a10": 1.2523, "a11": 2.2936,
        "a20": 1.9727, "a21": 8.3983,
        "a30": 6.0229, "a31": 1.4087,
    },
    "ga_best": {
        # Best-fit parameters from GA optimizer (DEAP, gen 28, fitness=0.3942)
        # mrk97_07 mean=1.1759 (target 1.2013), mrk97_08 mean=0.8634 (target 0.7922)
        "tau_effca_GB_GluSynapse": 278.3177658387,
        "gamma_d_GB_GluSynapse":    94.698202,
        "gamma_p_GB_GluSynapse":   211.404335,
        # a-params: theta_d/theta_p computed per-synapse from c_pre/c_post
        "a00": 1.000406, "a01": 1.954000,
        "a10": 1.160326, "a11": 2.590750,
        "a20": 1.164831, "a21": 2.489699,
        "a30": 3.670398, "a31": 1.566718,
    },
}


if __name__ == "__main__":
    workdir = os.getcwd()

    parser = argparse.ArgumentParser(
        description="Run induction sim; read synapse params from dhuruva_modified_edges.h5"
    )
    parser.add_argument(
        "--params", choices=list(PARAM_PRESETS.keys()),
        help="Named parameter preset for global GluSynapse HOC vars (e.g. chindemi)",
    )
    parser.add_argument(
        "--fastforward", type=float, default=None,
        help="Fast-forward start point in ms (default: no fast-forward)",
    )
    parser.add_argument(
        "--edges-h5", default=sim_mod.EDGES_H5_DEFAULT,
        help=f"Path to dhuruva_modified_edges.h5 (default: {sim_mod.EDGES_H5_DEFAULT})",
    )
    parser.add_argument(
        "--output-filename", default=None,
        help="Output pickle filename (default: simulation_edges.pkl)",
    )
    parser.add_argument(
        "--traces-output-dir", default=None,
        help=(
            "If given, simulation_traces.pkl is written to "
            "<traces-output-dir>/<pair_name>/<protocol>/simulation_traces.pkl "
            "instead of bluecellulab_results/ inside the workdir."
        ),
    )
    parser.add_argument(
        "--bluecellulab-output-dir", default=None,
        help=(
            "If given, rho.h5 / rho_timeseries.npy are written to "
            "<bluecellulab-output-dir>/<pair_name>/<protocol>/bluecellulab_results/ "
            "instead of bluecellulab_results/ inside the workdir."
        ),
    )
    parser.add_argument(
        "--cpre-cpost-cache", default=None,
        help=(
            "Path to precomputed c_pre/c_post cache pkl "
            "(generated by precompute_cpre_cpost.py). "
            "Skips mini-sims when the pair is found in the cache."
        ),
    )
    parser.add_argument(
        "--circuit-config", default=None,
        help=(
            "Override the 'network' field in prefire_simulation_config.json with this "
            "circuit config path. Applied only to the in-memory temp copy — the on-disk "
            "config is not modified. Useful for testing alternative cell models without "
            "regenerating workdirs (e.g. dhuruva_modified_ion_channels_circuit_config.json)."
        ),
    )
    parser.add_argument(
        "--bcl-subdir", default="bluecellulab_results",
        help=(
            "Name of the output subdirectory inside each workdir (or bluecellulab-output-dir) "
            "where rho.h5 and rho_timeseries.npy are written. "
            "Default: bluecellulab_results. Use a different name (e.g. "
            "bluecellulab_results_ion_channels) to avoid overwriting existing results."
        ),
    )
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(name)s %(levelname)s %(message)s",
    )
    log = logging.getLogger(__name__)

    fit_params = dict(PARAM_PRESETS[args.params]) if args.params else {}

    log.info("workdir          : %s", workdir)
    log.info("params           : %s", args.params or "(none)")
    log.info("fastforward      : %s ms", args.fastforward or "disabled")
    log.info("edges_h5         : %s", args.edges_h5)
    log.info("traces_output_dir: %s", args.traces_output_dir or "(workdir/bluecellulab_results)")
    log.info("bcl_output_dir   : %s", args.bluecellulab_output_dir or "(workdir/bluecellulab_results)")
    log.info("bcl_subdir       : %s", args.bcl_subdir)
    if args.circuit_config:
        log.info("circuit_config   : %s", args.circuit_config)
    if args.cpre_cpost_cache:
        log.info("cpre_cpost_cache : %s", args.cpre_cpost_cache)

    t_start = time.time()
    results = sim_mod.runconnectedpair_prefire_from_edges(
        workdir,
        fit_params=fit_params or None,
        edges_h5=args.edges_h5,
        fastforward=args.fastforward,
        traces_output_dir=args.traces_output_dir,
        bluecellulab_output_dir=args.bluecellulab_output_dir,
        cpre_cpost_cache=args.cpre_cpost_cache,
        circuit_config=args.circuit_config,
        bcl_subdir=args.bcl_subdir,
    )
    elapsed = time.strftime("%H:%M:%S", time.gmtime(time.time() - t_start))
    log.info("Simulation finished in %s", elapsed)

    filename = args.output_filename or "simulation_edges.pkl"
    out_path = os.path.join(workdir, filename)
    with open(out_path, "wb") as f:
        pickle.dump(results, f, protocol=-1)
    log.info("Results saved → %s", out_path)
